const ActionTypes = {
  userLocation: {
    GET_USER_LOCATION_REQUEST: 'GET_USER_LOCATION_REQUEST',
    GET_USER_LOCATION_SUCCESS: 'GET_USER_LOCATION_SUCCESS',
    GET_USER_LOCATION_FAILURE: 'GET_USER_LOCATION_FAILURE',
  },
  userRepositories: {
    GET_USER_REPOSITORIES_REQUEST: 'GET_USER_REPOSITORIES_REQUEST',
    GET_USER_REPOSITORIES_SUCCESS: 'GET_USER_REPOSITORIES_SUCCESS',
    GET_USER_REPOSITORIES_FAILURE: 'GET_USER_REPOSITORIES_FAILURE',
  },
  userLanguages: {
    GET_USER_LANGUAGES_REQUEST: 'GET_USER_LANGUAGES_REQUEST',
    GET_USER_LANGUAGES_SUCCESS: 'GET_USER_LANGUAGES_SUCCESS',
    GET_USER_LANGUAGES_FAILURE: 'GET_USER_LANGUAGES_FAILURE',
  },
};

export default ActionTypes;
