const Skills = [
  { key: 'ada', value: 'ada', text: 'Ada' },
  { key: 'algol', value: 'algol', text: 'ALGOL' },
  { key: 'apl', value: 'apl', text: 'APL' },
  { key: 'applescript', value: 'applescript', text: 'AppleScript' },
  { key: 'autoit', value: 'autoit', text: 'AutoIt' },
  { key: 'basic', value: 'basic', text: 'BASIC' },
  { key: 'bliss', value: 'bliss', text: 'bliss' },
  { key: 'c', value: 'c', text: 'C' },
  { key: 'c++', value: 'C++', text: 'C++' },
  { key: 'c#', value: 'C#', text: 'C#' },
  { key: 'charity', value: 'charity', text: 'Charity' },
  { key: 'chuck', value: 'chuck', text: 'chucK' },
  { key: 'clean', value: 'clean', text: 'Clean' },
  { key: 'cleo', value: 'cleo', text: 'CLEO' },
  { key: 'clist', value: 'clist', text: 'CLIST' },
  { key: 'COBOL', value: 'COBOL', text: 'COBOL' },
  { key: 'cobra', value: 'cobra', text: 'Cobra' },
  { key: 'component pascal', value: 'component pascal', text: 'Component Pascal' },
  { key: 'curry', value: 'curry', text: 'Curry' },
  { key: 'd', value: 'd', text: 'D' },
  { key: 'dasl', value: 'dasl', text: 'DASL' },
  { key: 'dibol', value: 'dibol', text: 'DIBOL' },
  { key: 'eiffel', value: 'eiffel', text: 'Eiffel' },
  { key: 'erlang', value: 'erlang', text: 'Erlang' },
  { key: 'f#', value: 'f#', text: 'F#' },
  { key: 'forth', value: 'forth', text: 'Forth' },
  { key: 'fortran', value: 'fortran', text: 'Fortran' },
  { key: 'frink', value: 'frink', text: 'Frink' },
  { key: 'game maker language', value: 'game maker language', text: 'Game Maker Language' },
  { key: 'haskell', value: 'haskell', text: 'Haskell' },
  { key: 'hypertalk', value: 'hypertalk', text: 'HyperTalk'},
  { key: 'ici', value: 'ici', text: 'ICI' },
  { key: 'j', value: 'j', text: 'J' },
  { key: 'java', value: 'java', text: 'Java' },
  { key: 'jovial', value: 'jovial', text: 'JOVIAL' },
  { key: 'joy', value: 'joy', text: 'Joy' },
  { key: 'kite', value: 'kite', text: 'Kite' },
  { key: 'lisp', value: 'lisp', text: 'Lisp' },
  { key: 'lua', value: 'lua', text: 'Lua' },
  { key: 'matlab', value: 'matlab', text: 'MATLAB' },
  { key: 'ml', value: 'ml', text: 'ML'},
  { key: 'modula-2', value: 'modula-2', text: 'Modula-2' },
  { key: 'mumps', value: 'mumps', text: 'MUMPS' },
  { key: 'nemerle', value: 'nemerle', text: 'Nemerle' },
  { key: 'oberon', value: 'oberon', text: 'Oberon' },
  { key: 'objective-c', value: 'objective-c', text: 'Objective-C' },
  { key: 'occam', value: 'occam', text: 'Occam' },
  { key: 'opal', value: 'opal', text: 'OPAL' },
  { key: 'ops5', value: 'ops5', text: 'OPS5' },
  { key: 'pascal', value: 'pascal', text: 'Pascal' },
  { key: 'pcastl', value: 'pcastl', text: 'PCASTL' },
  { key: 'perl', value: 'perl', text: 'Perl' },
  { key: 'pl/c', value: 'pl/c', text: 'PL/C' },
  { key: 'pl/i', value: 'pl/i', text: 'PL/I' },
  { key: 'postscript', value: 'postscript', text: 'PostScript' },
  { key: 'python', value: 'python', text: 'Python' },
  { key: 'q', value: 'q', text: 'Q' },
  { key: 'rapira', value: 'rapira', text: 'Rapira' },
  { key: 'rexx', value: 'rexx', text: 'REXX' },
  { key: 'rpg', value: 'rpg', text: 'RPG' },
  { key: 'ruby', value: 'ruby', text: 'Ruby' },
  { key: 's-lang', value: 's-lang', text: 'S-Lang' },
  { key: 'scala', value: 'scala', text: 'Scala' },
  { key: 'scheme', value: 'scheme', text: 'Scheme' },
  { key: 'small', value: 'small', text: 'SMALL' },
  { key: 'smalltalk', value: 'smalltalk', text: 'Smalltalk' },
  { key: 'spin', value: 'spin', text: 'Spin' },
  { key: 'turing', value: 'turing', text: 'Turing' },
  { key: 'visual basic', value: 'visual basic', text: 'Visual Basic' },
  { key: 'visual foxpro', value: 'visual foxpro', text: 'Visual FoxPro' },
  { key: 'xl', value: 'xl', text: 'XL' },
];

export default Skills;
