const Skills = [
  { key: 'ada', value: 'ada', text: 'Ada' },
  { key: 'algol', value: 'algol', text: 'ALGOL' },
  { key: 'apl', value: 'apl', text: 'APL' },
  { key: 'autoit', value: 'autoit', text: 'AutoIt' },
  { key: 'basic', value: 'basic', text: 'BASIC' },
  { key: 'c', value: 'c', text: 'C' },
  { key: 'c++', value: 'C++', text: 'C++' },
  { key: 'c#', value: 'C#', text: 'C#' },
  
  { key: 'charity', value: 'charity', text: 'Charity' },
  { key: 'clean', value: 'clean', text: 'Clean' },
  { key: 'curry', value: 'curry', text: 'Curry' },
  { key: 'eiffel', value: 'eiffel', text: 'Eiffel' },
  { key: 'erlang', value: 'erlang', text: 'Erlang' },
  { key: 'f#', value: 'f#', text: 'f#' },
  { key: 'forth', value: 'forth', text: 'Forth' },
  { key: 'frink', value: 'frink', text: 'Frink' },
  { key: 'game maker language', value: 'game maker language', text: 'Game Maker Language' },
  { key: 'haskell', value: 'haskell', text: 'haskell' },
  { key: 'ici', value: 'ici', text: 'ICI' },
  { key: 'j', value: 'j', text: 'J' },
  { key: 'joy', value: 'joy', text: 'Joy' },
  { key: 'kite', value: 'kite', text: 'Kite' },
  { key: 'lisp', value: 'lisp', text: 'Lisp' },
  { key: 'lua', value: 'lua', text: 'Lua' },
  { key: 'ml', value: 'ml', text: 'ML'},
  { key: 'mumps', value: 'mumps', text: 'MUMPS' },
  { key: 'nemerle', value: 'nemerle', text: 'Nemerle' },
  { key: 'opal', value: 'opal', text: 'OPAL' },
  { key: 'ops5', value: 'ops5', text: 'OPS5' },
  { key: 'pascal', value: 'pascal', text: 'Pascal' },
  { key: 'pcastl', value: 'pcastl', text: 'PCASTL' },
  { key: 'perl', value: 'perl', text: 'Perl' },
  { key: 'postscript', value: 'postscript', text: 'PostScript' },
  { key: 'python', value: 'python', text: 'Python' },
  { key: 'q', value: 'q', text: 'Q' },
  { key: 'rexx', value: 'rexx', text: 'REXX' },
  { key: 'ruby', value: 'ruby', text: 'Ruby' },
  { key: 's-lang', value: 's-lang', text: 'S-Lang' },
  { key: 'spin', value: 'spin', text: 'Spin' },
];

export default Skills;
